apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-k8s-demo
  template:
    metadata:
      labels:
        app: springboot-k8s-demo
    spec:
      containers:
      - name: springboot-k8s-demo-container
        image: rbalekundri/springboot-k8s-demo:1.1
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          value: "qa"
---
apiVersion: v1
kind: service
metadata:
  name: springboot-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-k8s-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
