spring:
  application:
    name: springboot-k8s-demo
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: true
server:
  error:
    whitelabel:
      enabled: false
APP_ENV: dev
